# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "yarn"
    directory: "/"
    target-branch: "upgrades"
    schedule:
      interval: "daily"
